[package]
name = "perl-xs-macro-support"
version = "0.1.0"
authors = ["perl-xs authors"]
license = "BSD-2-Clause"
edition = "2018"

[dependencies]
syn = { version = "0.15.39", features = ["full", "extra-traits"] }
quote = "0.6"
proc-macro2 = "0.4.30"