sudo: false # run in a docker container
language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
env:
  - TRAVIS_RUST_VERSION=stable
  - TRAVIS_RUST_VERSION=beta
  - TRAVIS_RUST_VERSION=nightly

before_install:
  - curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
  - rustc --version
  - rustup --version
  - cargo --version

script:
  - cd t/
  - perl Makefile.PL && make test
