[package]
name = "perl-xs-macro-derive"
version = "0.1.0"
authors = ["perl-xs Authors"]
edition = "2018"

[lib]
name = "perl_xs_macro_derive"
proc-macro = true

[dependencies]
syn = "0.11.11"
quote = "0.3.15"
perl-xs-macro-support = { path = "../macro-support" }